[package]
edition = "2024"
name = "github_integration"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }

# Path dependencies
foreign_entity_db_client = { path = "../foreign_entity_db_client" }
macro_uuid = { path = "../macro_uuid" }
model = { path = "../model" }
model-entity = { path = "../model-entity" }
